### ISSUE TITLE
No required 'packaging' module installed

### ISSUE THREAD

**Issue by vmartyanov** [0x48piraj/jiraffe#6]
Installed Jiraffe using pip:
`pip install jiraffe`
Tried to run and got import exception:
`C:\Python37\Scripts>jiraffe
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\jiraffe.exe\__main__.py", line 4, in <module>
  File "c:\python37\lib\site-packages\jiraffe\__main__.py", line 5, in <module>
    from .recon import request, isjira, getversion
  File "c:\python37\lib\site-packages\jiraffe\recon.py", line 8, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'`

I think something in pip manifest should me changed to install packaging module

**Comment by 0x48piraj** [comment]
Can you update your pip version,

```
pip3 install --upgrade pip
```

And then try to install packaging, if it's not already present.

```
pip3 install packaging
```

**Comment by vmartyanov** [comment]
After manually installing "packaging" everything works fine

**Comment by hackerpain** [comment]
still doesn't work.

with pip3 getting command not found

with pip getting syntax error of some sort
