### ISSUE TITLE
cannot run 

### ISSUE THREAD

**Issue by hxhBrofessor** [0x48piraj/jiraffe#8]
root@wmfb-xps:/usr/local/bin# ./jiraffe 
Traceback (most recent call last):
  File "./jiraffe", line 11, in <module>
    load_entry_point('jiraffe==2.0.1', 'console_scripts', 'jiraffe')()
  File "/usr/local/lib/python3.8/dist-packages/jiraffe-2.0.1-py3.8.egg/jiraffe/__main__.py", line 48, in main
TypeError: 'str' object is not callable

**Comment by 0x48piraj** [comment]
Refer to #5 (fixed)
